name: sonetto
description: aplicativo pessoal de música com sincronização supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^16.3.0
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  dio: ^5.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.6.0
  flex_color_scheme: ^8.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.3.3
  collection: ^1.18.0
  youtube_explode_dart: ^2.3.5
  spotify: ^0.13.7
  ffmpeg_kit_flutter_new: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/mock/
    - .env
