name: sonetto
description: aplicativo pessoal de música com sincronização supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  just_audio: ^0.9.40
  audio_session: ^0.1.19
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0
  flex_color_scheme: ^7.3.1
  path_provider: ^2.1.3
  uuid: ^4.3.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/mock/
    - .env
